on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
jobs:
  ci:
    uses: nr1etech/github-workflows/.github/workflows/javascript-library-build.yml@main
    with:
      node-versions: "[18,20,22]"
